"""
Constants and configurations - SOFT VERSION
"""
class PDFConstants:
    # Soft Colors (RGB) - Professional & Easy on Eyes
    PRIMARY_COLOR = (59, 89, 152)      # #3B5998 - Soft Blue
    SECONDARY_COLOR = (72, 87, 117)    # #485775 - Soft Dark Blue
    SUCCESS_COLOR = (46, 125, 50)      # #2E7D32 - Soft Green
    WARNING_COLOR = (237, 108, 0)      # #ED6C00 - Soft Orange
    DANGER_COLOR = (211, 47, 47)       # #D32F2F - Soft Red
    LIGHT_COLOR = (245, 245, 245)      # #F5F5F5 - Soft Light Gray
    BORDER_COLOR = (224, 224, 224)     # #E0E0E0 - Soft Border Gray
    
    # Fonts
    DEFAULT_FONT = "helvetica"
    BOLD_FONT = "helvetica"
    ITALIC_FONT = "helvetica"
    
    # Sizes
    PAGE_WIDTH = 210  # A4 width in mm
    PAGE_HEIGHT = 297  # A4 height in mm
    MARGIN = 15
    LINE_HEIGHT = 5
    
    # System defaults
    SYSTEM_CONFIG = {
        "name": "EDU-MANAGER PRO",
        "version": "2.0.0",
        "domain": "edumanager.ac.tz",
        "support_email": "support@edumanager.ac.tz",
        "footer_text": "Generated by EduManager Pro",
        "confidential": True
    }