"""
Constants and configurations
"""
class PDFConstants:
    # Colors (RGB)
    PRIMARY_COLOR = (41, 128, 185)    # #2980B9 - Blue
    SECONDARY_COLOR = (44, 62, 80)    # #2C3E50 - Dark Blue
    SUCCESS_COLOR = (39, 174, 96)     # #27AE60 - Green
    WARNING_COLOR = (241, 196, 15)    # #F1C40F - Yellow
    DANGER_COLOR = (231, 76, 60)      # #E74C3C - Red
    LIGHT_COLOR = (248, 249, 250)     # #F8F9FA - Light Gray
    BORDER_COLOR = (221, 221, 221)    # #DDDDDD - Gray
    
    # Fonts
    DEFAULT_FONT = "helvetica"
    BOLD_FONT = "helvetica"
    ITALIC_FONT = "helvetica"
    
    # Sizes
    PAGE_WIDTH = 210  # A4 width in mm
    PAGE_HEIGHT = 297  # A4 height in mm
    MARGIN = 10
    LINE_HEIGHT = 5
    
    # System defaults
    SYSTEM_CONFIG = {
        "name": "EDU-MANAGER PRO",
        "version": "3.0",
        "domain": "edumanager.ac.tz",
        "support_email": "support@edumanager.ac.tz",
        "support_phone": "+255 123 456 789",
        "company": "EduManager Solutions Ltd",
        "footer_text": "Generated by EduManager Pro - Confidential"
    }