"""
Base PDF template using fpdf2
"""
from fpdf import FPDF
from datetime import datetime
from .constants import PDFConstants

class BasePDFTemplate(FPDF):
    """Base class for all PDF generators"""
    
    def __init__(self, config: dict = None):
        super().__init__()
        self.config = {**PDFConstants.SYSTEM_CONFIG, **(config or {})}
        self.constants = PDFConstants
        
        # Basic setup
        self.set_margins(
            PDFConstants.MARGIN, 
            PDFConstants.MARGIN, 
            PDFConstants.MARGIN
        )
        self.set_auto_page_break(auto=True, margin=15)
        
        # Add first page
        self.add_page()
        self._setup_fonts()
    
    def _setup_fonts(self):
        """Setup fonts - can be overridden for custom fonts"""
        # Using default Helvetica font
        self.set_font(PDFConstants.DEFAULT_FONT, "", 10)
    
    def header(self):
        """Header template - override in child classes"""
        pass
    
    def footer(self):
        """Footer with page numbers and system info"""
        self.set_y(-15)
        self.set_font(PDFConstants.DEFAULT_FONT, "I", 8)
        self.set_text_color(*PDFConstants.SECONDARY_COLOR)
        
        # Page number
        page_num = f"Page {self.page_no()}"
        self.cell(0, 10, page_num, 0, 0, 'C')
        
        # System info at bottom left
        self.set_y(-15)
        self.set_x(10)
        footer_text = self.config.get("footer_text", "Generated by EduManager Pro")
        self.cell(0, 10, footer_text, 0, 0, 'L')
    
    def add_title(self, text: str, size: int = 16):
        """Add centered title"""
        self.set_font(PDFConstants.BOLD_FONT, "B", size)
        self.set_text_color(*PDFConstants.PRIMARY_COLOR)
        self.cell(0, 10, text, 0, 1, 'C')
        self.ln(5)
        self.reset_styles()
    
    def add_subtitle(self, text: str, size: int = 12):
        """Add subtitle"""
        self.set_font(PDFConstants.BOLD_FONT, "B", size)
        self.set_text_color(*PDFConstants.SECONDARY_COLOR)
        self.cell(0, 8, text, 0, 1, 'L')
        self.ln(3)
        self.reset_styles()
    
    def add_paragraph(self, text: str, align: str = 'L'):
        """Add paragraph"""
        self.set_font(PDFConstants.DEFAULT_FONT, "", 10)
        self.multi_cell(0, 5, text, align=align)
        self.ln(5)
    
    def add_separator(self):
        """Add horizontal line separator"""
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)
    
    def reset_styles(self):
        """Reset to default styles"""
        self.set_font(PDFConstants.DEFAULT_FONT, "", 10)
        self.set_text_color(0, 0, 0)
    
    def add_page_break(self):
        """Add page break and preserve header"""
        self.add_page()