"""
services/pdf_reports/base_template.py - FIXED
"""
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

class BasePDFTemplate:
    """Base template with system branding - FIXED VERSION"""
    
    def __init__(self, system_config=None):
        self.system_config = system_config or self._default_config()
        self.styles = getSampleStyleSheet()
        self._setup_styles()
    
    def _default_config(self):
        """System metadata for footer"""
        return {
            "system_name": "EDU-MANAGER PRO",
            "version": "2.0",
            "copyright": f"© {datetime.now().year} EduManager Pro",
            "support": "support@edumanager.com",
            "author": "EDU-MANAGER REPORT SYSTEM",
            "generator": "Python ReportLab"
        }
    
    def _setup_styles(self):
        """Setup PDF styles - FIXED no alpha parameter"""
        self.styles.add(ParagraphStyle(
            name='Footer',
            parent=self.styles['Normal'],
            fontSize=7,
            textColor=colors.grey,
            alignment=1  # Center
        ))
        
        self.styles.add(ParagraphStyle(
            name='Watermark',
            parent=self.styles['Normal'],
            fontSize=40,
            textColor=colors.lightgrey  # FIXED: Use lightgrey instead of HexColor with alpha
        ))
    
    def add_footer(self, canvas, doc):
        """Add system footer to every page"""
        try:
            canvas.saveState()
            canvas.setFont('Helvetica', 7)
            canvas.setFillColor(colors.grey)
            
            footer_text = f"{self.system_config['system_name']} v{self.system_config['version']} | {self.system_config['copyright']} | Page {canvas.getPageNumber()}"
            canvas.drawCentredString(doc.width/2, 15, footer_text)
            
            canvas.drawString(40, 15, datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
            canvas.drawRightString(doc.width + doc.leftMargin - 40, 15, 
                                 f"Generated by: {self.system_config['author']}")
            
            canvas.restoreState()
        except Exception as e:
            logger.warning(f"Footer error: {e}")
    
    def add_watermark(self, canvas, doc):
        """Add watermark if needed - FIXED VERSION"""
        try:
            canvas.saveState()
            canvas.setFont('Helvetica-Bold', 60)
            canvas.setFillColorRGB(0.9, 0.9, 0.9, alpha=0.1)  # FIXED: Use setFillColorRGB with alpha
            canvas.rotate(45)
            canvas.drawCentredString(doc.width/2, doc.height/3, 
                                   self.system_config['system_name'])
            canvas.restoreState()
        except Exception as e:
            logger.warning(f"Watermark error: {e}")
            # Alternative without alpha
            try:
                canvas.saveState()
                canvas.setFont('Helvetica-Bold', 60)
                canvas.setFillColor(colors.lightgrey)
                canvas.rotate(45)
                canvas.drawCentredString(doc.width/2, doc.height/3, 
                                       self.system_config['system_name'])
                canvas.restoreState()
            except:
                pass  # Skip watermark if it fails
    
    def safe_hex_color(self, hex_code, alpha=1.0):
        """Safe way to use hex colors with alpha"""
        try:
            # Remove # if present
            hex_code = hex_code.lstrip('#')
            
            # Convert to RGB
            r = int(hex_code[0:2], 16) / 255.0
            g = int(hex_code[2:4], 16) / 255.0
            b = int(hex_code[4:6], 16) / 255.0
            
            return (r, g, b, alpha)
        except:
            # Default to grey
            return (0.5, 0.5, 0.5, alpha)